apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: /:dad84883a4987e1e78606f6a3efa2b25c879d51c
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
