apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: /:7b32aef2a0afcb997e92881ad3daf1073b910ac2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
