apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: /:95c82c3b7fede42e3490c82a17cf2d4705d6d43b
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
