apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: /:7ae85c1e8acb8e6cab36051f393ef7147a773a2a
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
