apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: /:265af12cc5fa18d2cfbbac2e54556fb035772426
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
