apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: /:38dee39c1b51979f8d61119ef370b5a09cf3f000
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
