apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: docker.io/expense-tracker:ab16a9e4ff705a7fe4288acdc319a1b1126838b4
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
