apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: /:7306801f9a7c5b1bc79d19b4192a1b5a55a625cc
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
