apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: /:eb7fa0afdf329ebf8c7a4cfa7e3ccbdd8eca239e
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
