apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: /:a62210730548b403d5fbffac4e51875b6062e999
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
