apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: /:452974f7b7a7fd5004a01eb448bade84c92681de
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
