apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: /:b96fbe0c7d30f8126638d137e641ba47e3356a05
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
