apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: /:bd5fd6de0a4fb0073b6ae13790c79d5fe65ea1d9
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
