apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: my-namespace  # Убедитесь, что указан правильный namespace
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

