apiVersion: v1
kind: Service
metadata:
  name: expense-tracker
spec:
  type: NodePort
  selector:
    app: expense-tracker
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30001  # Убедитесь, что этот порт указан, если хотите использовать конкретный порт
