name: Build Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: windows-latest  # Windows Runner

    env:
      REGISTRY: docker.io
      IMAGE_NAME: expense-tracker
      USERNAME: olegmukhin

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t olegmukhin/expense-tracker:latest .
              
    # Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push olegmukhin/expense-tracker:latest 
