name: Kubernetes Deployment (Using kind)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Используем Windows-окружение для GitHub Actions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker-in-Docker
        run: |
          # Устанавливаем Docker и Docker-in-Docker
          choco install docker-cli docker-compose -y

      - name: Install kind
        run: |
          Invoke-WebRequest -Uri https://kind.sigs.k8s.io/dl/v0.17.0/kind-windows-amd64 -OutFile kind.exe
          Move-Item kind.exe -Destination "C:\Program Files\kind\kind.exe"
          $env:PATH += ";C:\Program Files\kind"

      - name: Create Kubernetes cluster with kind
        run: |
          kind create cluster

      - name: Install kubectl
        run: |
          Invoke-WebRequest -Uri https://storage.googleapis.com/kubernetes-release/release/v1.22.0/bin/windows/amd64/kubectl.exe -OutFile kubectl.exe
          Move-Item kubectl.exe -Destination "C:\Program Files\kubectl\kubectl.exe"
          $env:PATH += ";C:\Program Files\kubectl"

      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f deployment.yaml

      - name: Verify Kubernetes Deployment
        run: |
          kubectl get pods





