name: Kubernetes Deployment (Windows)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Используем Windows-окружение для GitHub Actions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up WSL for Minikube
        run: |
          # Устанавливаем WSL для работы с Minikube
          Invoke-WebRequest -Uri https://aka.ms/wsl-installer -OutFile wsl-installer.exe
          Start-Process wsl-installer.exe -ArgumentList "/install" -Wait

      - name: Install Minikube
        run: |
          # Устанавливаем Minikube через WSL
          wsl curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-windows-amd64
          wsl chmod +x minikube
          wsl mv minikube /usr/local/bin/

      - name: Start Minikube Cluster
        run: |
          # Запускаем Minikube в WSL
          wsl minikube start --driver=docker

      - name: Set kubeconfig
        run: |
          # Копируем конфиг Minikube в WSL
          wsl mkdir -p /home/$USER/.kube
          wsl cp /etc/kubernetes/admin.conf /home/$USER/.kube/config

      - name: Set up kubectl
        run: |
          # Устанавливаем kubectl в WSL
          wsl curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.22.0/bin/linux/amd64/kubectl
          wsl chmod +x ./kubectl
          wsl mv ./kubectl /usr/local/bin/kubectl

      - name: Apply Kubernetes Deployment
        run: |
          # Применяем деплоймент в Minikube
          wsl kubectl apply -f deployment.yaml

      - name: Verify Kubernetes Deployment
        run: |
          # Проверяем, что все работает
          wsl kubectl get pods


