name: Kubernetes Deployment (Using Minikube)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем Linux-окружение для GitHub Actions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo mv minikube-linux-amd64 /usr/local/bin/minikube
          sudo chmod +x /usr/local/bin/minikube

      - name: Start Minikube Cluster
        run: |
          minikube start --driver=docker

      - name: Install kubectl
        run: |
          curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.22.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl

      # Настроим kubectl для работы с Minikube
      - name: Set kubectl context
        run: |
          kubectl config use-context minikube

      # Применяем deployment.yaml
      - name: Apply Kubernetes Deployment
        run: |
          kubectl apply -f deployment.yaml

      # Получаем список подов
      - name: Verify Kubernetes Deployment
        run: |
          docker run -p 3000:3000 olegmukhin/expense-tracker:latest



