name: Secret

on:
  push:
    branches:
      - main  # или выберите другую ветку, для которой хотите запускать workflow
  workflow_dispatch:  # позволяет вручную запускать workflow через интерфейс GitHub
  
jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create directory for kubeconfig
        run: |
          # Используем стандартный временный путь, доступный в GitHub Actions
          $dirPath = "$env:TEMP\kube"
          if (-not (Test-Path -Path $dirPath)) {
            New-Item -ItemType Directory -Path $dirPath
          }

      - name: Save kubeconfig
        run: |
          $kubeconfig = $env:KUBERNETES_CONFIG
          # Записываем конфиг в файл в созданную директорию
          Set-Content -Path "$env:TEMP\kube\config" -Value "$kubeconfig"
        env:
          KUBERNETES_CONFIG: ${{ secrets.KUBERNETES_CONFIG }}

      - name: Verify kubeconfig file
        run: |
          Get-Content "$env:TEMP\kube\config"


