name: Secret

on:
  push:
    branches:
      - main  # или выберите другую ветку, для которой хотите запускать workflow
  workflow_dispatch:  # позволяет вручную запускать workflow через интерфейс GitHub

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Save kubeconfig to file
        run: |
          $kubeconfig = $env:KUBERNETES_CONFIG
          Set-Content -Path "C:\Users\Olegg\.kube\config" -Value $kubeconfig
        env:
          KUBERNETES_CONFIG: ${{ secrets.KUBERNETES_CONFIG }}

      - name: Verify kubeconfig file
        run: |
          Get-Content "C:\Users\Olegg\.kube\config"

