name: Build and Test Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-docker:
    runs-on: windows-latest  # используем Windows Runner для Docker

    env:
      REGISTRY: docker.io
      IMAGE_NAME: expense-tracker
      USERNAME: olegmukhin

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Run Docker container and test it
      - name: Run Docker container
        shell: pwsh
        run: |
          docker run -d -p 3000:3000 --name expense-tracker olegmukhin/expense-tracker:latest
          Start-Sleep -Seconds 10  # Wait for the container to fully start
          docker ps  # Verify if the container is running

      # Test if the application is accessible
      - name: Test if app is running
        shell: pwsh
        run: |
          try {
            Invoke-WebRequest -Uri "http://localhost:3000/api/healthcheck" -UseBasicParsing
          } catch {
            Write-Host "Healthcheck failed"
            exit 1
          }

      # Stop and remove the container
      - name: Stop and remove the container
        shell: pwsh
        run: |
          docker stop expense-tracker
          docker rm expense-tracker

